name = "Test 1"
board = """

 @AB  

 @CD  

  EF  @
"""

[symbols]
"@" = """\
#####
#   #
#   #
#   #
#####"""

A = """\
###
# #
  # 
  # #
  ###"""

B = """\
#####
#  #
#####
    #
#####"""

C = """\
# ###
# # #
#####
# # #
### #"""

D = """\
### #
#   #
#####
# # #
# ###"""

E = """
  ###
  # #
#####
# #
###  """

F = """\
#   #
#####
  #
# # #
#####
"""